### ISSUE TITLE
Frame.html is never loaded

### ISSUE THREAD

**Issue by kunte0** [spookjs/spookjs-poc#3]
`<iframe id="frame"></iframe>`

should be 

`<iframe id="frame" src="frame.html"></iframe>`

i assume. 

It would be a better test if it would not be same-origin but still same-site.

**Comment by siolioconnell** [comment]
The frame is loaded after initialization of spook.js. We load them one after the other because they both try to perform a cache side channel to determine the page offset of an array and can disrupt each other if loaded simultaneously.

https://github.com/spookjs/spookjs-poc/blob/main/static/js/main-worker.js#L237
https://github.com/spookjs/spookjs-poc/blob/main/static/js/main.js#L176-L177

Yes same-site not same-origin would have been a better test, though I think the user would have to change their DNS configuration so they could use subdomains for localhost.

**Comment by kunte0** [comment]
I think it never got so far that it loaded the frame for me so i was confused.
